name: Python CI/CD Pipeline

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install necessary packages
        uses: make install
      
      - name: Check code
        run: make refactor
    
      - name: Test code
        run: make test