name: Rust CI/CD Pipeline

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      work_dir: prime_numbers

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Format code
        run: make format
        working-directory: ${{ env.work_dir }}

      - name: Check code
        run: make check
        working-directory: ${{ env.work_dir }}
      
      - name: Test functionality
        run: cargo test
        working-directory: ${{ env.work_dir }}
      
      - name: Build binary artifact
        run: cargo build --release
        working-directory: ${{ env.work_dir }}
      
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rust Binary Artifact
          path: ${{ env.work_dir }}/target/release/prime_numbers